apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.namespace }}-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.global.namespace }}-ingress
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - host: dev-api.medulla.pfitz.co.zw
    - http:
        paths:
          - path: /whatsapp
            pathType: Prefix
            backend:
              service:
                name: medulla-whatsapp-service
                port:
                  number: 3000