apiVersion: v1
kind: Secret
metadata:
  name: medulla-secret
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
